import type { CollectionConfig } from "payload";
import { isStaff } from "../access-network";
import { readMarketInsightSnapshots, denySnapshotMutation } from "../access-market-pulse";

/**
 * Phase 17 — Blueprint §37 Market Pulse (PHASE17-TECHNICAL-DESIGN.md §C/
 * §D/§E/§G). Stores the *output* of aggregation, never the raw source
 * records — one row per (insightType, tier) as of the most recent compute.
 * `lib/network/market-pulse-engine.ts` is the only writer.
 *
 * Deliberately no relationship fields at all — every bucket is a
 * `{label, count}` pair inside the `buckets` json array, never a foreign
 * key back to a `BusinessProfile`/`CrmLead`/etc. This is the design's own
 * mitigation for the exact class of bug PHASE16-RELEASE-REVIEW.md's
 * Finding 1 caught in `getCrmOpenTasks` (a `depth: 1`/`overrideAccess: true`
 * populate leaking a foreign document's fields): there is nothing here for
 * any read helper to over-populate, at any depth, ever.
 *
 * Each compute REPLACES the existing row for its (insightType, tier) pair
 * rather than accumulating history — see the engine's `upsertSnapshot` for
 * why: v1 has no rolling-window/trend-over-time requirement (out of this
 * phase's approved scope), so keeping only the latest snapshot avoids an
 * ever-growing table for no current benefit.
 */
export const MarketInsightSnapshots: CollectionConfig = {
  slug: "market-insight-snapshots",
  labels: { singular: "Market Insight Snapshot", plural: "Market Insight Snapshots" },
  admin: {
    group: "Market Pulse",
    useAsTitle: "insightType",
    defaultColumns: ["insightType", "tier", "computedAt", "totalContributingRecords", "suppressedCount"],
    description: "System-generated by lib/network/market-pulse-engine.ts. Never hand-authored, including by Admin — see access-market-pulse.ts.",
  },
  indexes: [{ fields: ["insightType", "tier"], unique: true }],
  access: {
    read: readMarketInsightSnapshots,
    create: denySnapshotMutation,
    update: denySnapshotMutation,
    delete: ({ req: { user } }) => isStaff(user),
  },
  fields: [
    {
      name: "insightType",
      type: "select",
      required: true,
      options: [
        { label: "Industry Insights", value: "industry" },
        { label: "Opportunity Trends", value: "opportunity" },
        { label: "Service Demand Trends", value: "service-demand" },
        { label: "Regional Trends", value: "regional" },
        { label: "CRM Aggregated Insights", value: "crm-aggregate" },
      ],
    },
    {
      name: "tier",
      type: "select",
      required: true,
      options: [
        { label: "Public", value: "public" },
        { label: "Institutional", value: "institutional" },
      ],
      admin: { description: "Public = coarse, capped, readable by anyone. Institutional = fuller breakdown, gated to entitled institution accounts. Both are suppressed by the same k-anonymity rule — see PHASE17-TECHNICAL-DESIGN.md §G." },
    },
    { name: "computedAt", type: "date", required: true, admin: { description: "When this snapshot was generated. `lib/network/market-pulse.ts` treats a snapshot older than 24h as stale and recomputes on next read." } },
    {
      name: "buckets",
      type: "json",
      admin: { description: "Array of {label, count, group?}. Aggregate counts only — never a reference to an individual profile, posting, or CRM record." },
    },
    { name: "suppressedCount", type: "number", defaultValue: 0, admin: { description: "How many candidate buckets were withheld by the k-anonymity threshold this compute. Never reveals which ones — a transparency figure only." } },
    { name: "totalContributingRecords", type: "number", defaultValue: 0, admin: { description: "Sum of counts across every kept bucket that represents an actual record count — excludes any `group: \"rate\"` bucket, which holds a computed percentage, not a count. Not itself a bucket, and not suppressible — it never identifies an individual record." } },
  ],
};
